modal-encadeado/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('teste.urls', namespace='teste'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

teste/urls.py
from django.conf.urls import url
from .views import *
urlpatterns = [

url(r'^pais/listarcriar/$', PaisListCreateView.as_view(), name='pais-listarcriar'),
url(r'^pais/remover/$', paisDelete, name='pais-remover'),
url(r'^pais/editar/$', paisUpdate, name='pais-editar'),


]

teste/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):
    pais = models.CharField(max_length=50, verbose_name='País')
    bandeira = models.ImageField(null=True, blank=True)

    class Meta:
        verbose_name = 'País'
        verbose_name_plural = 'Países'

    def __str__(self):
        return self.pais


class Estado(models.Model):
    estado = models.CharField(max_length=50, verbose_name='Estado')
    pais = models.ForeignKey(Pais)

    def __str__(self):
        return self.estado

teste/forms.py
from django.forms import ModelForm
from .models import *

class PaisMF(ModelForm):
    class Meta:
        model = Pais
        fields = '__all__'

class EstadoMF(ModelForm):
    class Meta:
        model = Estado
        fields = '__all__'

teste/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .forms import *
from .models import Pais

class PaisListCreateView(CreateView):
    model = Pais
    form_class = PaisMF
    template_name = 'teste/pais-listarcriar.html'
    success_url = reverse_lazy('teste:pais-listarcriar')

    def get_context_data(self, ** kwargs):
        context = super(PaisListCreateView, self).get_context_data(**kwargs)
        context['object_list'] = self.model.objects.all()
        return context

def paisDelete(request):
    print('entrou no deletar')
    print(request.POST.get('id'))
    if request.method == 'POST' and request.POST.get('id') != None :
        pais = request.POST.get('id')
        pais_deletar = Pais.objects.get(id=pais)
        pais_deletar.delete()
        print('deletado')
        return HttpResponseRedirect('/pais/listarcriar')
    return redirect('/pais/listarcriar')

def paisUpdate(request):
    print('entrou no editar')
    print(request.POST.get('id'))
    if request.method == 'POST' and request.POST.get('id') != None :
        pais = request.POST.get('id')
        pais_editar = Pais.objects.get(id=pais)
        pais_editar.pais = request.POST.get('pais')
        if request.FILES.get('bandeira') == None:
            pais_editar.bandeira = request.POST.get('bandeiraexiste')[7:]
        else:
            pais_editar.bandeira = request.FILES.get('bandeira')
        pais_editar.save()
        print('editado')
        return HttpResponseRedirect('/pais/listarcriar')
    return redirect('/pais/listarcriar')

teste/templates/teste/pais-listarcriar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Teste de Modal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<section>
    <div class="container">
        <br>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal-pais-criar">Criar País</button>
        <br>
        <br>
        <table class="table table-bordered table-hovered" cellspacing="0" id="pais-table">
            <tr>
                <th>Países</th>
                <th>Bandeiras</th>
                <th>Ações</th>
            </tr>

            {% for pais in object_list %}
            <tr>
                <td>{{ pais.pais }}</td>
                <td><img src="{{ pais.bandeira.url }}" height="100" width="200"></td>
                <td>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-pais-visualizar" data-whatever="{{pais.id}}" data-whateverpais="{{pais.pais}}" data-whateverbandeira="{{pais.bandeira.url}}">Visualizar</button>
                    <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modal-pais-editar" data-whatever="{{pais.id}}" data-whateverpais="{{pais.pais}}" data-whateverbandeira="{{pais.bandeira.url}}">Editar</button>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-pais-remover" data-whatever="{{pais.id}}" data-whateverpais="{{pais.pais}}">Remover</button>
                </td>
            </tr>
            {% empty %}
            <h1>Nenhuma país cadastrado</h1>
            {% endfor %}
        </table>


        <!-- Modal criar-->
        <div id="modal-pais-criar" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">CRIAR PAÍS</h4>
                    </div>
                    <div class="modal-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.pais.label}}
                            <input type="text" class="form-control" name="{{form.pais.name}}" autofocus>
                            <br>
                            <input type="file" class="form-control" name="{{form.bandeira.name}}">
                            <br>
                            <button class="btn-success center-block" type="submit">Salvar</button>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>

            </div>
        </div>

        <!-- Modal visualizar -->
        <div class="modal fade" id="modal-pais-visualizar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">País</h4>
                    </div>
                    <div class="modal-body">
                        <label id="id_pais_visualizar"></label>
                        <br>
                        <h1 id="name_pais_visualizar"></h1>
                        <br>
                        <img id="bandeira_pais_visualizar" src="" height="100" width="200">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal editar-->
        <div id="modal-pais-editar" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">EDITAR PAÍS</h4>
                    </div>
                    <div class="modal-body">
                        <form method="post" enctype="multipart/form-data" action="{% url 'teste:pais-editar' %}">
                            {% csrf_token %}
                            <input type="hidden" class="form-control" name="id" id="id_pais_editar">
                            <br>
                            <input type="text" class="form-control" value="" name="pais" id="name_pais_editar" required autofocus>
                            <br>
                             Escolha uma imagem ou deixe sem para manter a atual!
                            <input type="hidden" class="form-control" name="bandeiraexiste" id="bandeira_existe_pais_editar">
                            <input type="file" class="form-control" name="bandeira">
                            <br>
                            <button class="btn-warning center-block" type="submit" >Editar</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>



        <!-- Modal remover-->
        <div id="modal-pais-remover" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">REMOVER PAÍS</h4>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'teste:pais-remover' %}">
                            {% csrf_token %}
                            <input type="hidden" class="form-control" name="id" id="id_pais_remover">
                            <br>
                            <h1 id="name_pais_remover"></h1>
                            <button class="btn-danger center-block" type="submit"  >Remover</button>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>

            </div>
        </div>
    </div>



</section>

<script>
//visualizar
$('#modal-pais-visualizar').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var id_pais = button.data('whatever')
  var name_pais = button.data('whateverpais')
  var bandeira_pais = button.data('whateverbandeira')

  var modal = $(this)
  modal.find('#id_pais_visualizar').text(id_pais)
  modal.find('#name_pais_visualizar').text(name_pais)
  modal.find('#bandeira_pais_visualizar').attr('src', bandeira_pais)
});

//editar
$('#modal-pais-editar').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var id_pais = button.data('whatever')
  var name_pais = button.data('whateverpais')
  var bandeira_pais = button.data('whateverbandeira')

  var modal = $(this)
  modal.find('#id_pais_editar').val(id_pais)
  modal.find('#name_pais_editar').val(name_pais)
  modal.find('#bandeira_existe_pais_editar').val(bandeira_pais)
});

//remover
$('#modal-pais-remover').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var id_pais = button.data('whatever')
  var name_pais = button.data('whateverpais')

  var modal = $(this)
  modal.find('#id_pais_remover').val(id_pais)
  modal.find('#name_pais_remover').text(name_pais)
});

</script>


</body>
</html>